### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by mruz** [srchea/PHP-Push-WebSocket#12]
Sometimes socket_write() throws `unable to write to socket`:
```
string(78) "ErrorException[2]: socket_write(): unable to write to socket [32]: Broken pipe"
string(96) "/test/vendor/srchea/php-push-web-socket/src/PushWebSocket/Server.php[308]"
string(848) "Trace: 
#0 /test/vendor/srchea/php-push-web-socket/src/PushWebSocket/Server.php(308): socket_write(Resource id #26, '�I am waiting 2 seconds', 24)
#1 /test/vendor/srchea/php-push-web-socket/src/PushWebSocket/Server.php(294): PushWebSocket\Server->send(Object(PushWebSocket\Client), 'I am waiting 2 seconds')
#2 /test/vendor/srchea/php-push-web-socket/src/PushWebSocket/Server.php(250): PushWebSocket\Server->startProcess(Object(PushWebSocket\Client))
#3 /test/app/modules/shell/tasks/WebsocketTask.php(25): PushWebSocket\Server->run()
```

**Comment by srchea** [comment]
How can we reproduce that?

**Comment by mruz** [comment]
For me it happens when:
Run your code in the verbose mode.
Add another client (eg. 3).
Close some tab (eg. 2) in the web browser.
Wait a moment.

I'm using:
openSUSE Tumblewed 20160117
php-fpm 5.6.17 (cli)

**Comment by mruz** [comment]
@srchea did you reproduce it?

**Comment by mruz** [comment]
I think I haven't `window.onbeforeunload`, so it works, but how about `Performing action: �` and receiving data from client after exit?

```php
[2016-04-05 02:30:57] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:30:57] Finding the socket that associated to the client...
[2016-04-05 02:30:57] Client found
[2016-04-05 02:30:57] Receiving data from the client #570369a4e4a62
[2016-04-05 02:30:57] Performing action: quit
[2016-04-05 02:30:57] Killing a child process
[2016-04-05 02:30:57] Process 14502 is killed!
[2016-04-05 02:30:57] Finding the socket that associated to the client...
[2016-04-05 02:30:57] Client found
[2016-04-05 02:30:57] Receiving data from the client #570369a4e4a62
[2016-04-05 02:30:57] Performing action: �
[2016-04-05 02:31:03] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:08] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:18] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:27] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:37] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:43] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:52] Send 'Client ID: 570369a70e990' to client #570369a70e990
[2016-04-05 02:31:57] Finding the socket that associated to the client...
[2016-04-05 02:31:57] Client found
[2016-04-05 02:31:57] Receiving data from the client #570369a4e4a62
[2016-04-05 02:31:57] Disconnecting client #570369a4e4a62
[2016-04-05 02:31:57] Socket closed
[2016-04-05 02:31:57] Client #570369a4e4a62 disconnected
```

I added `disconnect` if action is `exit`:
```php
if ($action == "exit" || $action == "quit") {
    //...
    $this->disconnect($client);
```

And now:
```php
[2016-04-05 02:39:58] Finding the socket that associated to the client...
[2016-04-05 02:39:58] Client found
[2016-04-05 02:39:58] Receiving data from the client #57036bc2e484b
[2016-04-05 02:39:58] Performing action: quit
[2016-04-05 02:39:58] Killing a child process
[2016-04-05 02:39:58] Process 14614 is killed!
[2016-04-05 02:39:58] Disconnecting client #57036bc2e484b
[2016-04-05 02:39:58] Socket closed
[2016-04-05 02:39:58] Client #57036bc2e484b disconnected
```

Is it good?

**Comment by srchea** [comment]
@mruz Nope, it wasn't able to reproduce it. :( Yes, when you close a tab, the client sends a 'quit' action: `ws.send('quit');` to the WebSocket server!

**Comment by mruz** [comment]
Still `broken pipe`. Maybe `window.onbeforeunload` not cover all exits?

> ErrorException[2]: socket_write(): unable to write to socket [32]: Broken pipe
on line
```php
 if (socket_write($client->getSocket(), $text, strlen($text)) === false) {
```

> ErrorException[2]: socket_shutdown(): unable to shutdown socket [107]: Transport endpoint is not connected
```php
socket_shutdown($client->getSocket(), 2);
```

**Comment by srchea** [comment]
I'll check :)

**Comment by mruz** [comment]
Thanks, maybe we can check `socket_last_error()` before `socket_write()`?
